### ISSUE TITLE
"Astralenergie" does not honour special skill "Gefäß der Sterne"

### ISSUE THREAD

**Issue by kreuvf** [kreuvf/roll20-character-sheets#9]
With "Gefäß der Sterne" the formula for AE calculation changes from `0.5 * (MU + IN + CH)` to `CH + 0.5 * (MU + IN)` increasing the AE by at least 7 AsP.

**Comment by Markus1204** [comment]
That's a thing, yes. But normally you'd use something like "Helden-Software" or so to generate a Char and just carry the values over to the Sheet in Roll20...

In DSA 5 Sheet it is possible to select Advantages and Disadvantages from a checklist in the charsheet directly. With this I think it would be easier to do the calculation in the sheet automatically but since this is not the case... well...

**Comment by kreuvf** [comment]
"Gefäß der Sterne" can be acquired later in the game. Therefore, it makes sense to have it in the sheet as well.
